[package]
name = "stock_cli"
version = "0.1.0"
authors = ["Braden Mabey <braden.mabey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
